server:
  path:
    working-directory: /home/sexde/OVPN4ALL
  script:
    user:
      create:
        config: CreateUserVPNFile.sh
        cert: CreateUserCert.sh
      delete: DeleteUser.sh
    server:
      create:
        config: CreateServerConfig.sh
        cert: CreateServerCert.sh
