server:
  path:
    working-directory: /home/sexde/OVPN4ALL
  name:
    user:
      create:
        config: CreateUserVPNFile
        cert: CreateUserCert
      delete: DeleteUser
    server:
      download:
        logs: DownloadLogs
      create:
        config: CreateServerConfig
        cert: CreateServerCert